using System.Data;
using System.IO.Compression;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Hekutenantcoreapp.Infrastructure.Data;

// Bulk-loads reference / lookup tables from gzipped CSVs shipped under
// Resources/<folder>/<table>.csv.gz, using PostgreSQL COPY — but only for tables that are
// currently empty, so it is a no-op on every start after the first. Built for data that a
// fresh project database needs seeded (geography today; e.g. a course-subject catalog
// later): add the .csv.gz resource next to the others, wire the columns into a small named
// seeder (see GeographySeeder), and call that from Program.cs startup.
//
// Each CSV's first row is a header and is skipped. Ids are taken from the file as-is (the
// id column is GENERATED BY DEFAULT), and the identity sequence is advanced past them
// afterwards so a later plain insert cannot collide.
public static class CsvSeeder
{
    // `columns` is spliced into the COPY statement verbatim. It is always a
    // developer-authored constant, never user input — same trust level as migration SQL.
    public static async Task SeedAsync(DbContext db, string folder, params (string Table, string Columns)[] tables)
    {
        var conn = (NpgsqlConnection)db.Database.GetDbConnection();
        var openedHere = conn.State != ConnectionState.Open;
        if (openedHere) await conn.OpenAsync();

        try
        {
            foreach (var (table, columns) in tables)
                await SeedTableAsync(conn, folder, table, columns);
        }
        finally
        {
            if (openedHere) await conn.CloseAsync();
        }
    }

    private static async Task SeedTableAsync(NpgsqlConnection conn, string folder, string table, string columns)
    {
        await using (var check = new NpgsqlCommand($"SELECT EXISTS (SELECT 1 FROM {table})", conn))
            if ((bool)(await check.ExecuteScalarAsync())!)
                return;

        var path = Path.Combine(AppContext.BaseDirectory, "Resources", folder, $"{table}.csv.gz");
        if (!File.Exists(path))
            return;

        await using (var file = File.OpenRead(path))
        await using (var gzip = new GZipStream(file, CompressionMode.Decompress))
        using (var reader = new StreamReader(gzip))
        {
            // Drop the header row, then stream the body straight into COPY. Reading raw
            // chars (not lines) keeps any quoted field containing a newline intact.
            int ch;
            while ((ch = reader.Read()) != -1 && ch != '\n') { }

            await using var writer = await conn.BeginTextImportAsync(
                $"COPY {table} ({columns}) FROM STDIN (FORMAT csv)");

            var buffer = new char[81920];
            int read;
            while ((read = await reader.ReadAsync(buffer)) > 0)
                await writer.WriteAsync(buffer.AsMemory(0, read));
        }

        await using var resync = new NpgsqlCommand(
            $"SELECT setval(pg_get_serial_sequence('{table}', 'id'), (SELECT MAX(id) FROM {table}))", conn);
        await resync.ExecuteScalarAsync();
    }
}
